source:      .
destination: ./_site
plugins:     ./_plugins
uto: false
server: false
lsi: false
safe: false
pygments: true
markdown: rdiscount
rdiscount:
  extensions: [:generate_toc]

permalink: /:year/:month/:day/:title
paginate: 10
exclude: ["Rakefile", "CNAME", "Website.tmproj", "changelog.md"]
title: Bilal S Hussain
github_user: Bilalh
projects:
  "mplayer-last.fm-scrobbler":
    title: MPlayer last.fm Scrobbler
    # version: "1.1"  
    changelog: true
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application launchers such as LaunchBar or Alfred to quickly clear your screen.
  aaa:
    title: Nunc faucibus neque id nibh.
    version: "1.0"  
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application launchers such as LaunchBar or Alfred to quickly clear your screen.            
  fsfdsdfff:
    title: Nunc faucibus neque id nibh.
    version: "1.0"
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application launchers such as LaunchBar or Alfred to quickly clear your screen.            
  fffdsff:
    title: Nunc faucibus neque id nibh.
    version: "1.0"
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application launchers such as LaunchBar or Alfred to quickly clear your screen.
      
      
  ffgggf:
    title: Nunc faucibus neque id nibh.
    version: "1.0"
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application launchers such as LaunchBar or Alfred to quickly clear your screen.
        
  fdff:
    title: Nunc faucibus neque id nibh.
    version: "1.0"
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application launchers such as LaunchBar or Alfred to quickly clear your screen.     