source:      .
destination: ./_site
plugins:     ./_plugins
uto: false
server: false
lsi: false
safe: false
pygments: true
paginate: 2
paginate_files: 
  - blog.html 

indextank_index: my_index
indextank_api_url: http://:oj1Uxwu56zAgHx@dcz51.api.indextank.com
# these values are applied as regular expressions 
indextank_excludes: [index.html, 404.html, ^/secret/] 

markdown: maruku
rdiscount:
  extensions: [:generate_toc]

permalink: /:year/:month/:day/:title
exclude: ["Rakefile", "CNAME", "Website.tmproj", "changelog.md"]
title: Bilal S Hussain
github_user: Bilalh
projects:
  "mplayer-last.fm-scrobbler":
    title: MPlayer last.fm Scrobbler
    icon:  "/images/VgTagger.png"
    version: "1.1"  
    languages: "Shell, C++"
    changelog: true  
  aaa:
    title: Nunc faucibus neque id nibh.
    version: "1.0"                              
    languages: "Objective C, Ruby, C++"  
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application            
  fsfdsdfff:
    title: Nunc faucibus neque id nibh.
    version: "1.0"
    languages: "Shell, C++"  
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application launchers such as LaunchBar or Alfred to quickly clear your screen.            
  fffdsff:
    title: Nunc faucibus neque id nibh.
    version: "1.0"          
    languages: "Shell, C++"  
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application launchers such as LaunchBar or Alfred to quickly clear your screen.
      
      
  ffgggf:
    title: Nunc faucibus neque id nibh.
    version: "1.0"    
    languages: "Shell, C++"  
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application launchers such as LaunchBar or Alfred to quickly clear your screen.
        
  fdff:
    title: Nunc faucibus neque id nibh.
    version: "1.0"     
    languages: "Shell, C++"  
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application launchers such as LaunchBar or Alfred to quickly clear your screen.     