source:      .
destination: ./_site
plugins:     ./_plugins
uto:      false
server:   false
lsi:      false
safe:     false
pygments: true
paginate: 2
paginate_files: 
  - blog.html 

github_user:       Bilalh
indextank_index:   BsBlog
indextank_api_url: "http://:oj1Uxwu56zAgHx@dcz51.api.indextank.com"
# these values are applied as regular expressions 
indextank_excludes: [index.html, 404.html, ^/secret/] 

markdown: maruku
rdiscount:
  extensions: [:generate_toc]

permalink: /:year/:month/:day/:title
exclude:   ["Rakefile", "CNAME", "Website.tmproj", "changelog.md"]
title:     Bilal S Hussain

projects:
  mplayer-last.fm-scrobbler:
    title:     Tagger
    icon:      /images/VgTagger.png
    version:   1.3  
    languages: Objective C, Ruby, C++
    changelog: true
    apidocs:   true
    features:
        - title: Aqua User Interface
          icon:  /images/gui.png
          description: >
            Intuitive user interface based on technology that features everything you would expect from a good  Mac application, including time savers like **drag and drop**, **Quick Look**, and more.  
            
        - title: Batch Operations
          icon : /images/gui.png
          description: >
            **Multiple** file tag editing is easy since Tagger supports applying changes to a selection of files 

        - title: Auto Tagging
          icon : /images/gui.png
          description: >
            Tagger can **Search** for the tags off the internet. Tagger will retrieve matching result and allows you to browse the result and finally apply the tags to the selection.
        - title: Superior Tag Support
          icon : /images/gui.png
          description: Tagger supports nearly **all** of the tags of both **MP3** and **MP4**

  aaa:
    title: Nunc faucibus neque id nibh.
    version: "1.0"
    changelog: true                              
    languages: "Objective C, Ruby, C++"  
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application            
  fsfdsdfff:
    title: Nunc faucibus neque id nibh.
    version: "1.0"
    languages: "Shell, C++"  
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application launchers such as LaunchBar or Alfred to quickly clear your screen.            
  fffdsff:
    title: Nunc faucibus neque id nibh.
    version: "1.0"          
    languages: "Shell, C++"  
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application launchers such as LaunchBar or Alfred to quickly clear your screen.
      
      
  ffgggf:
    title: Nunc faucibus neque id nibh.
    version: "1.0"    
    languages: "Shell, C++"  
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application launchers such as LaunchBar or Alfred to quickly clear your screen.
        
  fdff:
    title: Nunc faucibus neque id nibh.
    version: "1.0"     
    languages: "Shell, C++"  
    description: A simple application for OS X that clears all your growl notifications. It's useful in conjunction with application launchers such as LaunchBar or Alfred to quickly clear your screen.     